Profile Configure Conditional Question Support
openflighthpc/flight-profile pull request #113
Opened 2023-09-11 13:13 UTC by Cena-Studio

# OverView
Along with the development of OpenFlight, the future `flight profile configure` may need to include more questions to provide users with a more comprehensive and customized service. Some of these questions will need to be determined based on the answer to the previous question, i.e., parent questions, leading to different branches. Finally, the question library will form a tree-like branching structure because of those sub-questions. This PR aims to provide better structural support for such questions, allowing question designers to easily design and manage questions through YAML files. In addition, This PR also add support for specifying a certian type of questions that requires the answers to be only yes/y or no/n.

## Example YAML Question File Content (Simplified)
```
questions:
  - id: question_1
    type: conditional
    questions:
      - id: question_1_1
        where: true
  - id: question_2
    questions:
      - id: question_2_1
        type: conditional
        where: 3n
        questions:
          - id: question_2_1_true
            where: true
          - id: question_2_1_false
            where: false
      - id: question_2_2
        where: 3n+1
      - id: question_2_3
        where: 3n+2
  - id: question_3
```
As can be seen from the above example, `question_1` is defined as a conditional question by the `type` parameter. `question_1_1` will only be raised when the answer to `question_1` is true as defined by the `where` parameter of `question_1_`1`.
`question_2` is a relatively more complicated example that contains three levels of hierarchies. In that case, `question_2_1_false` will only be raised when the user answers "3n" to `question_2` and then answers "no" or "n" for `question_2_1`.

2023-09-12 15:52 UTC, VoxSecundus commented
Please could you switch the target branch to `develop` and resolve the resulting merge conflict?

2024-01-09 10:20 UTC, ColonelPanicks commented
I think flight profile is still struggling with true/false variables, see:

```bash
[flight@gateway1 ~]$ flight profile configure
Cluster type:  Openflight Slurm Multinode
Cluster name: my-cluster
NFS server (hostname or flight-hunter label): gateway1
SLURM server (hostname or flight-hunter label): gateway1
Setup Multi User Environment with IPA? No
Local user login: flight
Set local user password to: 0penfl1ght
IP or FQDN for Web Access: 10.151.15.151
IP Range of Compute Nodes: 10.100.0.0/16

[root@gateway1 profile]# cat var/answers/openflight-slurm-multinode.yaml
---
cluster_name: my-cluster
nfs_server: gateway1
slurm_server: gateway1
ipa_use: false
default_username: flight
default_password: 0penfl1ght
access_host: 10.151.15.151
compute_ip_range: 10.100.0.0/16

[flight@gateway1 ~]$ flight profile list
┌──────────┬──────────┬───────────┐
│ Node     │ Identity │ Status    │
├──────────┼──────────┼───────────┤
│ gateway1 │          │ available │
│ node01   │          │ available │
│ node02   │          │ available │
└──────────┴──────────┴───────────┘

[flight@gateway1 ~]$ flight profile apply gateway1 login
profile: The following config keys have not been set:
setup multi user environment with IPA?
Please run `profile configure`
```

My `metadata.yaml` for `openflight-slurm-multinode`

```yaml
---
id: openflight-slurm-multinode
name: 'Openflight Slurm Multinode'
description: 'A Multi Node Research Environment running SLURM & NFS'
questions:
  - id: cluster_name
    env: CLUSTERNAME
    text: 'Cluster name:'
    default: my-cluster
    validation:
      type: string
      format: "^[a-zA-Z0-9_\\-]+$"
      message: 'Invalid cluster name: %{value}. Must contain only alphanumeric characters,
      - and _.'
  - id: nfs_server
    env: NFS_SERVER
    text: 'NFS server (hostname or flight-hunter label):'
    default: 'login1'
    default_smart:
      - "/opt/flight/bin/flight hunter list --plain |grep $(hostname -f) |awk '{print $5}'"
      - "hostname -s"
    validation:
      type: string
      format: "^(\\S)+$"
      message: "Cannot be empty or contain whitespace"
  - id: slurm_server
    env: SLURM_SERVER
    text: 'SLURM server (hostname or flight-hunter label):'
    default: 'login1'
    default_smart:
      - "/opt/flight/bin/flight hunter list --plain |grep $(hostname -f) |awk '{print $5}'"
      - "hostname -s"
    validation:
      type: string
      format: "^(\\S)+$"
      message: "Cannot be empty or contain whitespace"
  - id: ipa_use
    env: IPA_USE
    text: 'Setup Multi User Environment with IPA?'
    default: no
    type: conditional
    validation:
      type: string
      format: "^(?i)(true|false)$"
      message: "Must be either true or false"
    questions:
      - id: ipa_server
        env: IPA_SERVER
        text: 'IPA server (short hostname or flight-hunter label):'
        default: 'infra01'
        where: true
        validation:
          type: string
          format: "^(\\S)+$"
          message: "Cannot be empty or contain whitespace"
      - id: ipa_domain
        env: IPA_DOMAIN
        text: 'IPA domain:'
        default: 'cluster.example.com'
        where: true
        default_smart:
          - 'hostname -d'
        validation:
          type: string
          format: "^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$"
          message: "Domain name must contain at least 2 elements separated by '.' (e.g. 'example.com')"
      - id: secure_admin_password
        env: SECURE_ADMIN_PASSWORD
        text: 'IPA Secure Admin Password:'
        default: "MySecurePassword"
        where: true
        validation:
          type: string
          format: "^(\\S)+$"
          message: "Cannot be empty or contain whitespace"
  - id: default_username
    env: DEFAULT_USERNAME
    text: 'Local user login:'
    default: flight
    default_smart:
      - "cut -d: -f1,3 /etc/passwd | egrep ':[0-9]{4}$' | cut -d: -f1 |head -1" # First local user with UID of 1000 or higher
    validation:
      type: string
      format: "^(\\S)+$"
      message: "Cannot be empty or contain whitespace"
  - id: default_password
    env: DEFAULT_PASSWORD
    text: 'Set local user password to:'
    default: 0penfl1ght
    validation:
      type: string
  - id: access_host
    env: ACCESS_HOST
    text: 'IP or FQDN for Web Access:'
    default_smart:
      - "curl -s --fail http://169.254.169.254/latest/meta-data/public-hostname |grep -v novalocal" # Public Hostname from AWS/OpenStack Metadata (excluding default OpenStack domain name)
      - "curl -s --fail http://169.254.169.254/latest/meta-data/public-ipv4" # IP from AWS/OpenStack Metadata
      - "curl -s --fail -H Metadata:true http://169.254.169.254/metadata/instance/network/interface/0/ipv4/ipAddress/0?api-version=2021-12-13 |sed 's/.*publicIpAddress\":\"//g;s/\".*//g'" # IP from Azure Metadata
      - "curl -s ifconfig.me" # External IP curl
    validation:
      type: string
      format: "^(\\S)+$"
      message: "Cannot be empty or contain whitespace"
  - id: compute_ip_range
    env: COMPUTE_IP_RANGE
    text: 'IP Range of Compute Nodes:'
    default: '10.10.0.0/16'
    default_smart:
      - "ipcalc $(/usr/sbin/ip addr show $(/usr/sbin/ip -o -4 route show to default |awk '{print $5}') |grep 'inet ' |sed 's/.*inet //g;s/ brd.*//g') |grep '^Network:' |awk '{print $2}'"
    validation:
      type: string
      format: "^(\\S)+$"
      message: "Cannot be empty or contain whitespace"
```

2024-01-10 16:39 UTC, Cena-Studio commented
> I think flight profile is still struggling with true/false variables, see:
> 
> ```shell
> [flight@gateway1 ~]$ flight profile configure
> Cluster type:  Openflight Slurm Multinode
> Cluster name: my-cluster
> NFS server (hostname or flight-hunter label): gateway1
> SLURM server (hostname or flight-hunter label): gateway1
> Setup Multi User Environment with IPA? No
> Local user login: flight
> Set local user password to: 0penfl1ght
> IP or FQDN for Web Access: 10.151.15.151
> IP Range of Compute Nodes: 10.100.0.0/16
> 
> [root@gateway1 profile]# cat var/answers/openflight-slurm-multinode.yaml
> ---
> cluster_name: my-cluster
> nfs_server: gateway1
> slurm_server: gateway1
> ipa_use: false
> default_username: flight
> default_password: 0penfl1ght
> access_host: 10.151.15.151
> compute_ip_range: 10.100.0.0/16
> 
> [flight@gateway1 ~]$ flight profile list
> ┌──────────┬──────────┬───────────┐
> │ Node     │ Identity │ Status    │
> ├──────────┼──────────┼───────────┤
> │ gateway1 │          │ available │
> │ node01   │          │ available │
> │ node02   │          │ available │
> └──────────┴──────────┴───────────┘
> 
> [flight@gateway1 ~]$ flight profile apply gateway1 login
> profile: The following config keys have not been set:
> setup multi user environment with IPA?
> Please run `profile configure`
> ```
> 
> My `metadata.yaml` for `openflight-slurm-multinode`
> 
> ```yaml
> ---
> id: openflight-slurm-multinode
> name: 'Openflight Slurm Multinode'
> description: 'A Multi Node Research Environment running SLURM & NFS'
> questions:
>   - id: cluster_name
>     env: CLUSTERNAME
>     text: 'Cluster name:'
>     default: my-cluster
>     validation:
>       type: string
>       format: "^[a-zA-Z0-9_\\-]+$"
>       message: 'Invalid cluster name: %{value}. Must contain only alphanumeric characters,
>       - and _.'
>   - id: nfs_server
>     env: NFS_SERVER
>     text: 'NFS server (hostname or flight-hunter label):'
>     default: 'login1'
>     default_smart:
>       - "/opt/flight/bin/flight hunter list --plain |grep $(hostname -f) |awk '{print $5}'"
>       - "hostname -s"
>     validation:
>       type: string
>       format: "^(\\S)+$"
>       message: "Cannot be empty or contain whitespace"
>   - id: slurm_server
>     env: SLURM_SERVER
>     text: 'SLURM server (hostname or flight-hunter label):'
>     default: 'login1'
>     default_smart:
>       - "/opt/flight/bin/flight hunter list --plain |grep $(hostname -f) |awk '{print $5}'"
>       - "hostname -s"
>     validation:
>       type: string
>       format: "^(\\S)+$"
>       message: "Cannot be empty or contain whitespace"
>   - id: ipa_use
>     env: IPA_USE
>     text: 'Setup Multi User Environment with IPA?'
>     default: no
>     type: conditional
>     validation:
>       type: string
>       format: "^(?i)(true|false)$"
>       message: "Must be either true or false"
>     questions:
>       - id: ipa_server
>         env: IPA_SERVER
>         text: 'IPA server (short hostname or flight-hunter label):'
>         default: 'infra01'
>         where: true
>         validation:
>           type: string
>           format: "^(\\S)+$"
>           message: "Cannot be empty or contain whitespace"
>       - id: ipa_domain
>         env: IPA_DOMAIN
>         text: 'IPA domain:'
>         default: 'cluster.example.com'
>         where: true
>         default_smart:
>           - 'hostname -d'
>         validation:
>           type: string
>           format: "^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$"
>           message: "Domain name must contain at least 2 elements separated by '.' (e.g. 'example.com')"
>       - id: secure_admin_password
>         env: SECURE_ADMIN_PASSWORD
>         text: 'IPA Secure Admin Password:'
>         default: "MySecurePassword"
>         where: true
>         validation:
>           type: string
>           format: "^(\\S)+$"
>           message: "Cannot be empty or contain whitespace"
>   - id: default_username
>     env: DEFAULT_USERNAME
>     text: 'Local user login:'
>     default: flight
>     default_smart:
>       - "cut -d: -f1,3 /etc/passwd | egrep ':[0-9]{4}$' | cut -d: -f1 |head -1" # First local user with UID of 1000 or higher
>     validation:
>       type: string
>       format: "^(\\S)+$"
>       message: "Cannot be empty or contain whitespace"
>   - id: default_password
>     env: DEFAULT_PASSWORD
>     text: 'Set local user password to:'
>     default: 0penfl1ght
>     validation:
>       type: string
>   - id: access_host
>     env: ACCESS_HOST
>     text: 'IP or FQDN for Web Access:'
>     default_smart:
>       - "curl -s --fail http://169.254.169.254/latest/meta-data/public-hostname |grep -v novalocal" # Public Hostname from AWS/OpenStack Metadata (excluding default OpenStack domain name)
>       - "curl -s --fail http://169.254.169.254/latest/meta-data/public-ipv4" # IP from AWS/OpenStack Metadata
>       - "curl -s --fail -H Metadata:true http://169.254.169.254/metadata/instance/network/interface/0/ipv4/ipAddress/0?api-version=2021-12-13 |sed 's/.*publicIpAddress\":\"//g;s/\".*//g'" # IP from Azure Metadata
>       - "curl -s ifconfig.me" # External IP curl
>     validation:
>       type: string
>       format: "^(\\S)+$"
>       message: "Cannot be empty or contain whitespace"
>   - id: compute_ip_range
>     env: COMPUTE_IP_RANGE
>     text: 'IP Range of Compute Nodes:'
>     default: '10.10.0.0/16'
>     default_smart:
>       - "ipcalc $(/usr/sbin/ip addr show $(/usr/sbin/ip -o -4 route show to default |awk '{print $5}') |grep 'inet ' |sed 's/.*inet //g;s/ brd.*//g') |grep '^Network:' |awk '{print $2}'"
>     validation:
>       type: string
>       format: "^(\\S)+$"
>       message: "Cannot be empty or contain whitespace"
> ```

Thank you for pointing this out. It was caused by the same reason as the previous one but in another method. I've fixed and successfully tried to apply a node with the given metadata. Btw plz remove `validation format` for the conditional type questions since the answer won't be a string and cannot be validated by a regex.

2024-01-11 10:01 UTC, ColonelPanicks commented
> Btw plz remove validation format for the conditional type questions since the answer won't be a string and cannot be validated by a regex.

If I remove it I get the following error (as validation is _required_ by Flight Profile questions - not necessarily sure I agree that it should):
```
[flight@gateway1 ~]$ flight profile configure
Cluster type:  Openflight Slurm Multinode
Cluster name: condition1
NFS server (hostname or flight-hunter label): gateway1
SLURM server (hostname or flight-hunter label): gateway1
profile: undefined method `required' for nil:NilClass
```

2024-01-11 11:32 UTC, ColonelPanicks commented
I think this is still having issues in the case of answers when the conditional is true:
```bash
[flight@gateway1 ~]$ flight profile configure
Cluster type:  Openflight Slurm Multinode
Cluster name: condition4
NFS server (hostname or flight-hunter label): gateway1
SLURM server (hostname or flight-hunter label): gateway1
Setup Multi User Environment with IPA? yes
IPA server (short hostname or flight-hunter label): node01
IPA domain: conditionals4.alces.network
IPA Secure Admin Password: MySecurePassword
Local user login: flight
Set local user password to: 0penfl1ght
IP or FQDN for Web Access: 10.151.15.58
IP Range of Compute Nodes: 10.100.0.0/16
profile: undefined method `match' for true:TrueClass
```

The metadata.yaml for `openflight-slurm-multinode`:
```yaml
---
id: openflight-slurm-multinode
name: 'Openflight Slurm Multinode'
description: 'A Multi Node Research Environment running SLURM & NFS'
questions:
  - id: cluster_name
    env: CLUSTERNAME
    text: 'Cluster name:'
    default: my-cluster
    validation:
      type: string
      format: "^[a-zA-Z0-9_\\-]+$"
      message: 'Invalid cluster name: %{value}. Must contain only alphanumeric characters,
      - and _.'
  - id: nfs_server
    env: NFS_SERVER
    text: 'NFS server (hostname or flight-hunter label):'
    default: 'login1'
    default_smart:
      - "/opt/flight/bin/flight hunter list --plain |grep $(hostname -f) |awk '{print $5}'"
      - "hostname -s"
    validation:
      type: string
      format: "^(\\S)+$"
      message: "Cannot be empty or contain whitespace"
  - id: slurm_server
    env: SLURM_SERVER
    text: 'SLURM server (hostname or flight-hunter label):'
    default: 'login1'
    default_smart:
      - "/opt/flight/bin/flight hunter list --plain |grep $(hostname -f) |awk '{print $5}'"
      - "hostname -s"
    validation:
      type: string
      format: "^(\\S)+$"
      message: "Cannot be empty or contain whitespace"
  - id: ipa_use
    env: IPA_USE
    type: conditional
    text: 'Setup Multi User Environment with IPA?'
    default: 'false'
    validation:
      type: string
      format: "^(?i)(true|false)$"
      message: "Must be either true or false"
    questions:
      - id: ipa_server
        env: IPA_SERVER
        text: 'IPA server (short hostname or flight-hunter label):'
        default: 'infra01'
        where: true
        validation:
          type: string
          format: "^(\\S)+$"
          message: "Cannot be empty or contain whitespace"
      - id: ipa_domain
        env: IPA_DOMAIN
        text: 'IPA domain:'
        default: 'cluster.example.com'
        default_smart:
          - 'hostname -d'
        where: true
        validation:
          type: string
          format: "^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$"
          message: "Domain name must contain at least 2 elements separated by '.' (e.g. 'example.com')"
      - id: secure_admin_password
        env: SECURE_ADMIN_PASSWORD
        text: 'IPA Secure Admin Password:'
        default: "MySecurePassword"
        where: true
        validation:
          type: string
          format: "^(\\S)+$"
          message: "Cannot be empty or contain whitespace"
  - id: default_username
    env: DEFAULT_USERNAME
    text: 'Local user login:'
    default: flight
    default_smart:
      - "cut -d: -f1,3 /etc/passwd | egrep ':[0-9]{4}$' | cut -d: -f1 |head -1" # First local user with UID of 1000 or higher
    validation:
      type: string
      format: "^(\\S)+$"
      message: "Cannot be empty or contain whitespace"
  - id: default_password
    env: DEFAULT_PASSWORD
    text: 'Set local user password to:'
    default: 0penfl1ght
    validation:
      type: string
  - id: access_host
    env: ACCESS_HOST
    text: 'IP or FQDN for Web Access:'
    default_smart:
      - "curl -s --fail http://169.254.169.254/latest/meta-data/public-hostname |grep -v novalocal" # Public Hostname from AWS/OpenStack Metadata (excluding default OpenStack domain name)
      - "curl -s --fail http://169.254.169.254/latest/meta-data/public-ipv4" # IP from AWS/OpenStack Metadata
      - "curl -s --fail -H Metadata:true http://169.254.169.254/metadata/instance/network/interface/0/ipv4/ipAddress/0?api-version=2021-12-13 |sed 's/.*publicIpAddress\":\"//g;s/\".*//g'" # IP from Azure Metadata
      - "curl -s ifconfig.me" # External IP curl
    validation:
      type: string
      format: "^(\\S)+$"
      message: "Cannot be empty or contain whitespace"
  - id: compute_ip_range
    env: COMPUTE_IP_RANGE
    text: 'IP Range of Compute Nodes:'
    default: '10.10.0.0/16'
    default_smart:
      - "ipcalc $(/usr/sbin/ip addr show $(/usr/sbin/ip -o -4 route show to default |awk '{print $5}') |grep 'inet ' |sed 's/.*inet //g;s/ brd.*//g') |grep '^Network:' |awk '{print $2}'"
    validation:
      type: string
      format: "^(\\S)+$"
      message: "Cannot be empty or contain whitespace"
```

2024-01-11 14:08 UTC, ColonelPanicks commented
From IRL: The above is an issue caused by having `type` in the `validation` field for the conditional question, it causes profile to try and match it as a string, this is not an issue with the code

2024-01-11 14:21 UTC, ColonelPanicks commented
This LGTM. Will put together modifications to flight-profile-types to support this.

2024-01-15 11:52 UTC, VoxSecundus commented
@Cena-Studio Please could you rebase this on `develop` before I review it? :slightly_smiling_face:

2024-01-18 11:04 UTC, VoxSecundus requested changes
Really great work here. I don't remember if supporting deeper nesting of conditional questions was an original requirement, but I'm pleasantly surprised to see that it works. One rebase-related change to make, first.

2024-01-18 11:24 UTC, VoxSecundus commented
I've also pushed a rebase to this branch:
- Squashing the numerous line-endings fix commits into one
- Dropping the commit that had rewound a lot of work to an earlier version of `develop`

2024-01-18 14:10 UTC, Cena-Studio commented
An issue that the profile apply process didn't fetch the answer based on conditional questions has been fixed

2024-01-18 14:10 UTC, Cena-Studio commented on lib/profile/commands/configure.rb
> +            if !result.success?
This has been fixed

2024-01-18 17:26 UTC, VoxSecundus approved these changes
This LGTM. @ColonelPanicks I'm going to give you a chance to test this as it's had changes since you last looked at it; whether you do or don't, please post in this thread when you're ready to OK it.

2024-01-19 14:49 UTC, merged